# Physical parameters

dh_parameters:
  d1: 0.1625
  a2: -0.3520
  a3: -0.3715
  d4: 0.1345
  d5: 0.0965
  d6: 0.0920

inertia_parameters:
  base_mass: 0.57127  # base mass, base inertia, base cog might be incorrect
  shoulder_mass: 4.521
  upperarm_mass: 8.633
  forearm_mass: 3.71
  wrist_1_mass: 1.59
  wrist_2_mass: 1.47
  wrist_3_mass: 0.500

  inertia:
    base:
      ixx: 0.0010759
      ixy: 7.8337E-08
      ixz: -1.3213E-05
      iyy: 0.0010109
      iyz: 4.5992E-07
      izz: 0.001408
    shoulder:
      ixx: 0.014192
      ixy: 1.7839E-05
      ixz: -1.027E-06
      iyy: 0.0091982
      iyz: -4.6778E-05
      izz: 0.012777
    upperarm:
      ixx: 0.153469
      ixy: -7.2502E-05
      ixz: -0.191109
      iyy: 0.651187
      iyz: 8.15E-07
      izz: 0.513559
    forearm:
      ixx: 0.0113122
      ixy: 3.6957E-05
      ixz: -0.0022928
      iyy: 0.210332
      iyz: -2.993E-06
      izz: 0.205203
    wrist_1:
      ixx: 0.0045393
      ixy: -0.06E-06
      ixz: -4.094E-06
      iyy: 0.0042242
      iyz: 2.544E-06
      izz: 0.0014897
    wrist_2:
      ixx: 0.0024212
      ixy: -0.066E-06
      ixz: 4.088E-06
      iyy: 0.0020961
      iyz: 2.663E-06
      izz: 0.0013603
    wrist_3:
      ixx: 0.0014314
      ixy: -2.32E-07
      ixz: 7.955E-06
      iyy: 0.0014299
      iyz: 1.266E-06
      izz: 0.0003265

  center_of_mass:
    base_cog:
      x: -0.00060346
      y: 1.4311E-05
      z: 0.060221
    shoulder_cog:
      x: 2.2E-05
      y: -0.016526
      z: -0.014442
    upperarm_cog:
      x: -0.17590
      y: 1.0E-06
      z: 0.12588
    forearm_cog:
      x: -0.167631
      y: 1.26E-04
      z: 0.021397
    wrist_1_cog:
      x: -2.4E-05
      y: -0.004046
      z: -0.02239
    wrist_2_cog:
      x: 2.6E-05
      y: 0.004376
      z: -0.012432
    wrist_3_cog:
      x: -0.000684
      y: -0.000175
      z: -0.04234