# Default initial positions for er7robot's ros2_control fake system

initial_positions:
  camera_joint_1: 0.3
  camera_joint_2: 0.3
  camera_joint_3: 0.3
  camera_joint_4: 0.3
  camera_joint_5: 0.3
  camera_joint_6: 0.3
  laser_joint_1: 0.3
  laser_joint_2: 0.3
  laser_joint_3: 0.3
  laser_joint_4: 0.3
  laser_joint_5: 0.3
  laser_joint_6: 0.3