camera_arm_group:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.0050000000000000001
laser_arm_group:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.0050000000000000001

# camera_arm_group:
#   kinematics_solver: bio_ik/BioIKKinematicsPlugin
#   kinematics_solver_search_resolution: 0.0050000000000000001
#   kinematics_solver_timeout: 0.0050000000000000001
# laser_arm_group:
#   kinematics_solver: bio_ik/BioIKKinematicsPlugin
#   kinematics_solver_search_resolution: 0.0050000000000000001
#   kinematics_solver_timeout: 0.0050000000000000001