# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - camera_arm_group_controller
    - laser_arm_group_controller

  camera_arm_group_controller:
    type: FollowJointTrajectory
    joints:
      - camera_joint_1
      - camera_joint_2
      - camera_joint_3
      - camera_joint_4
      - camera_joint_5
      - camera_joint_6
    action_ns: follow_joint_trajectory
    default: true

  laser_arm_group_controller:
    type: FollowJointTrajectory
    joints:
      - laser_joint_1
      - laser_joint_2
      - laser_joint_3
      - laser_joint_4
      - laser_joint_5
      - laser_joint_6
    action_ns: follow_joint_trajectory
    default: false