controller_manager:
  ros__parameters:
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    
    io_and_status_controller:
      type: eli_cs_controllers/GPIOController

    speed_scaling_state_broadcaster:
      type: eli_cs_controllers/SpeedScalingStateBroadcaster

    scaled_joint_trajectory_controller:
      type: eli_cs_controllers/ScaledJointTrajectoryController
    
    freedrive_controller:
      type: eli_cs_controllers/FreedriveController

    tcp_pose_broadcaster:
      type: pose_broadcaster/PoseBroadcaster

force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: $(var tf_prefix)tcp_fts_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: $(var tf_prefix)tool0
    topic_name: ft_data

forward_position_controller:
  ros__parameters:
    joints:
      - $(var tf_prefix)shoulder_pan_joint
      - $(var tf_prefix)shoulder_lift_joint
      - $(var tf_prefix)elbow_joint
      - $(var tf_prefix)wrist_1_joint
      - $(var tf_prefix)wrist_2_joint
      - $(var tf_prefix)wrist_3_joint

joint_trajectory_controller:
  ros__parameters:
    joints:
      - $(var tf_prefix)shoulder_pan_joint
      - $(var tf_prefix)shoulder_lift_joint
      - $(var tf_prefix)elbow_joint
      - $(var tf_prefix)wrist_1_joint
      - $(var tf_prefix)wrist_2_joint
      - $(var tf_prefix)wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      $(var tf_prefix)shoulder_pan_joint: { trajectory:  0.9, goal: 0.1 }
      $(var tf_prefix)shoulder_lift_joint: { trajectory:  0.9, goal: 0.1 }
      $(var tf_prefix)elbow_joint: { trajectory: 0.9, goal: 0.1 }
      $(var tf_prefix)wrist_1_joint: { trajectory: 0.9, goal: 0.1 }
      $(var tf_prefix)wrist_2_joint: { trajectory:  0.9, goal: 0.1 }
      $(var tf_prefix)wrist_3_joint: { trajectory:  0.9, goal: 0.1 }

forward_velocity_controller:
  ros__parameters:
    joints:
      - $(var tf_prefix)shoulder_pan_joint
      - $(var tf_prefix)shoulder_lift_joint
      - $(var tf_prefix)elbow_joint
      - $(var tf_prefix)wrist_1_joint
      - $(var tf_prefix)wrist_2_joint
      - $(var tf_prefix)wrist_3_joint
    interface_name: velocity

io_and_status_controller:
  ros__parameters:
    tf_prefix: "$(var tf_prefix)"

speed_scaling_state_broadcaster:
  ros__parameters:
    state_publish_rate: 100.0
    tf_prefix: "$(var tf_prefix)"

scaled_joint_trajectory_controller:
  ros__parameters:
    joints:
      - $(var tf_prefix)shoulder_pan_joint
      - $(var tf_prefix)shoulder_lift_joint
      - $(var tf_prefix)elbow_joint
      - $(var tf_prefix)wrist_1_joint
      - $(var tf_prefix)wrist_2_joint
      - $(var tf_prefix)wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      $(var tf_prefix)shoulder_pan_joint: { trajectory: 0.9, goal: 0.1 }
      $(var tf_prefix)shoulder_lift_joint: { trajectory: 0.9, goal: 0.1 }
      $(var tf_prefix)elbow_joint: { trajectory:  0.9, goal: 0.1 }
      $(var tf_prefix)wrist_1_joint: { trajectory: 0.9, goal: 0.1 }
      $(var tf_prefix)wrist_2_joint: { trajectory: 0.9, goal: 0.1 }
      $(var tf_prefix)wrist_3_joint: { trajectory: 0.9, goal: 0.1 }
    speed_scaling_interface_name: $(var tf_prefix)speed_scaling/speed_scaling_factor

freedrive_controller:
  ros__parameters:
    tf_prefix: "$(var tf_prefix)"

tcp_pose_broadcaster:
  ros__parameters:
    frame_id: $(var tf_prefix)base
    pose_name: $(var tf_prefix)tcp_pose
    tf:
      child_frame_id: $(var tf_prefix)tool0_controller